site_name: CMTJ
site_url: https://lemurpwned.github.io/cmtj/
site_author: LemurPwned

repo_url: https://github.com/LemurPwned/cmtj
repo_name: LemurPwned/cmtj

edit_uri: ""

hooks:
  - scripts/readme_copy.py

nav:
  - Home: index.md
  - Overview: overview.md
  - Changelog: changelog.md
  - Tips & Tricks: tipsandtricks.md
  - Theory:
      - Macromagnetic contributions: physics/contributions.md
      - LLG Equation & solvers: physics/macromagnetic_models.md
      - Static Smit-Beljers model: physics/sb-model.md
  - Experimental:
      - Introduction: experimental-methods/introduction.md
      - CIMS: experimental-methods/CIMS.ipynb
      - Harmonic Hall: experimental-methods/HarmonicsFits.ipynb
      - Misc experiments: experimental-methods/examples.ipynb
      - Spin Diode experiments: experimental-methods/VoltageSpinDiodeFits.ipynb
  - Parallelism: physics/paralellism.md
  - API:
      - Core: api/core.md
      - Drivers: api/drivers.md
      - Models:
          - Smit-Beljers: api/models/sb-general-reference.md
          - Domain wall: api/models/dw-reference.md
      - Utils:
          - Resistance: api/resistance-reference.md
          - Linear: api/linear-reference.md
          - Filters: api/filters-reference.md
          - Energy: api/energy-reference.md
          - Plotting: api/plotting-reference.md
          - Procedures: api/procedures-reference.md
          - Parallel: api/parallel-reference.md
          - Optimization: api/optimization-reference.md
          - Ensemble models: api/ensemble-reference.md
          - Miscellanous: api/general-reference.md
      - Stack: api/stack.md
      - Noise: api/noise.md
      - LLGB: api/llgb.md
  - Examples:
      - Library introduction: tutorials/CMTJBindingsTutorial.ipynb
      - Trajectories: tutorials/trajectory.ipynb
      - Smit-Beljers: tutorials/SBModel.ipynb

theme:
  icon:
    repo: material/github
  name: "material"
  logo: assets/icon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: sphinx

  - mkdocs-jupyter:
      include_source: True
  - git-revision-date:
      enabled_if_env: CI
      enable_creation_date: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
