# This is a basic workflow to help you get started with Actions

name: Full package build


# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux-build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: build and upload manylinux wheels
        uses: Niraj-Kamdar/manylinux-wheel-builder@master  
        with:
          working-directory: /home/runner/spinpy/spinpy/cmtj
  
  
  other-os-build:
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        working-directory: /home/runner/spinpy/spinpy/cmtj
        run: |
          pip install wheel
          python setup.py bdist_wheel
      - name: upload wheel
        working-directory: /home/runner/spinpy/spinpy/cmtj
        run: |
          pip install twine
          twine upload dist/*
        continue-on-error: true
