name: Python Package Publication

on:
  pull_request:
    branches: [master]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.py'
      - 'setup.py'
      - 'setup.cfg'
      - 'pyproject.toml'
      - '**.yml'

  pull_request_target:
    types: [closed]
    branches: [master]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.py'
      - 'setup.py'
      - 'setup.cfg'
      - 'pyproject.toml'
      
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run (no actual upload to PyPI)'
        type: boolean
        default: true

jobs:
  linux-build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      IS_DRY_RUN: ${{ !(github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      # installing twice seems to help with the manylinux build
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel setuptools twine packaging>=24.2
      - name: Get version
        id: get_version
        run: |
          echo "version=$(python setup.py --version)" >> $GITHUB_OUTPUT
      - name: Python wheels manylinux stable build
        uses: RalfG/python-wheels-manylinux-build@v0.5.0
        with:
          python-versions: 'cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311 cp312-cp312'
      - name: Upload wheel
        env:
          TWINE_PASSWORD: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.merged == true && secrets.PYPI_TOKEN || secrets.TEST_PYPI_TOKEN }}
        run: |
          if [ "$IS_DRY_RUN" == "true" ]; then
            echo "Running in dry-run mode..."
            twine upload --repository testpypi dist/*-manylinux*.whl || echo "Dry run - would have uploaded wheels"
          else
            echo "Running in production mode..."
            twine upload dist/*-manylinux*.whl
          fi
        continue-on-error: ${{ env.IS_DRY_RUN == 'true' }}
    
  other-os-build:
    runs-on: ${{ matrix.os }}
    env:
      TWINE_USERNAME: __token__
      IS_DRY_RUN: ${{ !(github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Get version
        id: get_version
        run: |
          echo "version=$(python setup.py --version)" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          python -m pip install wheel setuptools twine packaging>=24.2
          python setup.py bdist_wheel
      - name: Upload wheel
        env:
          TWINE_PASSWORD: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.merged == true && secrets.PYPI_TOKEN || secrets.TEST_PYPI_TOKEN }}
        run: |
          if [ "$IS_DRY_RUN" == "true" ]; then
            echo "Running in dry-run mode..."
            twine upload --repository testpypi dist/* || echo "Dry run - would have uploaded wheels"
          else
            echo "Running in production mode..."
            twine upload dist/*
          fi
        continue-on-error: ${{ env.IS_DRY_RUN == 'true' }}
        
  release-build:
    needs: [ linux-build, other-os-build ]
    if: (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: get_version
        run: |
          echo "version=$(python setup.py --version)" >> $GITHUB_OUTPUT
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.get_version.outputs.version }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${{ steps.get_version.outputs.version }}" \
              --generate-notes
