# This is a basic workflow to help you get started with Actions

name: Python Package Publication

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release-version:
        required: true
      dry-run: 
        required: true
        default: true
        type: boolean
      linux:
        type: boolean
        required: true
        default: true
      other-os:
        type: boolean
        required: true
        default: true

jobs:
  linux-build:
    if: ${{ inputs.linux }} 
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Python wheels manylinux stable build
        uses: RalfG/python-wheels-manylinux-build@v0.5.0
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311'
      - name: upload wheel
        if:  ${{ !inputs.dry-run }} 
        run: |
          pip install twine
          twine upload dist/*-manylinux*.whl
        continue-on-error: false
    
  other-os-build:
    if: ${{ inputs.other-os }} 
    runs-on: ${{ matrix.os }}
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          pip install wheel
          python setup.py bdist_wheel
      - name: upload wheel
        if:  ${{ !inputs.dry-run }} 
        run: |
          pip install twine
          twine upload dist/*
        continue-on-error: false
        
  release-build:
    if:  ${{ !inputs.dry-run }} 
    needs: [ linux-build, other-os-build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: "package-release.zip"
        exclusions: '*.git* __pycache__/* .editorconfig build/* .eggs/*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "package-release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.release-version }}
